// Eventos
btn_areaS.addEventListener("click", squareA);
btn_areaR.addEventListener("click", rectangleA);
btn_areaT.addEventListener("click", triangleA);
btn_areaC.addEventListener("click", circleA);
btn_perimeterS.addEventListener("click", squareP);
btn_perimeterR.addEventListener("click", rectangleP);
btn_perimeterT.addEventListener("click", triangleP);
btn_perimeterC.addEventListener("click", circleP);
btn_radiusC.addEventListener("click", circleR);
btn_diameterC.addEventListener("click", circleD);
btn_circumferenceC.addEventListener("click", circleC);
